"""
Prediction and Inference Routes for ADR Risk Stratification
"""

from typing import Any, Dict, Tuple

from flask import Blueprint, Response, jsonify, request
from pydantic import ValidationError

from schemas import PatientDataSchema
from services.clinical_service import ClinicalService
from services.gemini_service import GeminiService
from services.ml_service import MLService, ModelNotReadyError

predict_bp = Blueprint("predict", __name__)


@predict_bp.route("/predict", methods=["POST"])
def predict() -> Tuple[Response, int]:
    """Execute ML prediction and return comprehensive ADR risk analysis"""
    if not request.is_json:
        return jsonify({"status": "error", "message": "Request must be JSON"}), 400

    raw_data = request.get_json()
    if not raw_data:
        return jsonify({"status": "error", "message": "Empty JSON payload"}), 400

    # Validate schema with Pydantic
    try:
        validated_schema = PatientDataSchema(**raw_data)
        patient_dict = validated_schema.model_dump()
    except ValidationError as e:
        return jsonify({"status": "validation_error", "errors": e.errors()}), 422
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 400

    # Execute ML inference
    ml_service = MLService.get_instance()
    try:
        result = ml_service.predict(patient_dict)
        return jsonify(result), 200
    except ModelNotReadyError as e:
        return jsonify({"status": "error", "message": str(e)}), 503
    except Exception as e:
        return jsonify({"status": "error", "message": f"Inference failed: {str(e)}"}), 500


@predict_bp.route("/mitigation_strategies", methods=["POST"])
def mitigation_strategies() -> Tuple[Response, int]:
    """
    Risk-prioritized mitigation plan.

    Previously a fixed list keyed only off risk_level, identical for every
    patient. Now generated by Gemini from the full clinical picture, with the
    original list retained as the offline fallback.
    """
    data = request.get_json() or {}
    patient_data = data.get("patient_data", {})
    prediction_result = data.get("prediction_result", {})

    gemini_service = GeminiService.get_instance()
    result = gemini_service.generate_mitigation_strategies(
        patient_data=patient_data, prediction_result=prediction_result
    )

    return jsonify({"status": "success", **result}), 200


@predict_bp.route("/sample_data/<sample_type>", methods=["GET"])
def sample_data(sample_type: str) -> Tuple[Response, int]:
    """
    Pre-built clinical profiles for demonstration and testing.

    Every key here is offered by the Quick Start selector on the assessment page.
    The previous implementation defined only two profiles and silently returned the
    elderly one for any unrecognised key, so all eight menu options produced
    identical data. Unknown keys now 404 rather than lying.
    """
    samples: Dict[str, Dict[str, Any]] = {
        "high_risk": {
            "name": "Harold Wilson",
            "age": 78,
            "sex": "M",
            "ethnicity": "White",
            "height": 172.0,
            "weight": 70.0,
            "bmi": 23.7,
            "creatinine": 2.2,
            "egfr": 28.0,
            "ast_alt": 65.0,
            "bilirubin": 1.2,
            "albumin": 3.4,
            "hemoglobin": 10.8,
            "platelet_count": 140000.0,
            "cyp2c9": "Poor",
            "cyp2d6": "PM",
            "cyp2c19": "PM",
            "medication_name": "Warfarin",
            "index_drug_dose": 7.5,
            "concomitant_drugs_count": 8,
            "polypharmacy_flag": 1,
            "prior_adr_history": 1,
            "high_risk_drug_flag": 1,
            "diabetes": 1,
            "ckd": 1,
            "cardiac_disease": 1,
            "hypertension": 1,
        },
        "medium_risk": {
            "name": "Maria Gonzalez",
            "age": 56,
            "sex": "F",
            "ethnicity": "Hispanic",
            "height": 162.0,
            "weight": 82.0,
            "bmi": 31.2,
            "creatinine": 1.1,
            "egfr": 62.0,
            "ast_alt": 48.0,
            "bilirubin": 1.0,
            "albumin": 3.9,
            "cyp2c9": "Intermediate",
            "cyp2d6": "IM",
            "medication_name": "Metformin",
            "index_drug_dose": 1000.0,
            "concomitant_drugs_count": 3,
            "diabetes": 1,
            "hypertension": 1,
        },
        "low_risk": {
            "name": "Sarah Miller",
            "age": 34,
            "sex": "F",
            "ethnicity": "Asian",
            "height": 165.0,
            "weight": 58.0,
            "bmi": 21.3,
            "creatinine": 0.8,
            "egfr": 110.0,
            "ast_alt": 20.0,
            "bilirubin": 0.6,
            "albumin": 4.5,
            "cyp2c9": "Wild",
            "cyp2d6": "EM",
            "medication_name": "Amoxicillin",
            "index_drug_dose": 500.0,
            "concomitant_drugs_count": 0,
            "prior_adr_history": 0,
        },
        "liver_disease": {
            "name": "Daniel Okafor",
            "age": 61,
            "sex": "M",
            "ethnicity": "Black",
            "height": 178.0,
            "weight": 74.0,
            "bmi": 23.4,
            "creatinine": 1.0,
            "egfr": 82.0,
            "ast_alt": 210.0,
            "bilirubin": 3.1,
            "albumin": 2.6,
            "platelet_count": 95000.0,
            "cyp3a4": "Poor",
            "medication_name": "Atorvastatin",
            "index_drug_dose": 40.0,
            "concomitant_drugs_count": 4,
            "liver_disease": 1,
            "high_risk_drug_flag": 1,
        },
        "cardiac_patient": {
            "name": "Eleanor Brooks",
            "age": 69,
            "sex": "F",
            "ethnicity": "White",
            "height": 160.0,
            "weight": 68.0,
            "bmi": 26.6,
            "creatinine": 1.4,
            "egfr": 45.0,
            "ast_alt": 38.0,
            "bilirubin": 0.9,
            "albumin": 3.7,
            "bp_systolic": 148.0,
            "bp_diastolic": 92.0,
            "heart_rate": 58.0,
            "medication_name": "Digoxin",
            "index_drug_dose": 0.25,
            "concomitant_drugs_count": 6,
            "polypharmacy_flag": 1,
            "cardiac_disease": 1,
            "hypertension": 1,
            "qt_prolonging_flag": 1,
            "high_risk_drug_flag": 1,
        },
        "renal_impairment": {
            "name": "Rajesh Kumar",
            "age": 64,
            "sex": "M",
            "ethnicity": "Asian",
            "height": 170.0,
            "weight": 66.0,
            "bmi": 22.8,
            "creatinine": 3.4,
            "egfr": 19.0,
            "ast_alt": 30.0,
            "bilirubin": 0.8,
            "albumin": 3.2,
            "hemoglobin": 9.6,
            "medication_name": "Lisinopril",
            "index_drug_dose": 20.0,
            "concomitant_drugs_count": 5,
            "polypharmacy_flag": 1,
            "ckd": 1,
            "diabetes": 1,
            "hypertension": 1,
        },
        "elderly_polypharmacy": {
            "name": "Margaret Fry",
            "age": 84,
            "sex": "F",
            "ethnicity": "White",
            "height": 155.0,
            "weight": 49.0,
            "bmi": 20.4,
            "creatinine": 1.6,
            "egfr": 32.0,
            "ast_alt": 44.0,
            "bilirubin": 1.1,
            "albumin": 3.1,
            "hemoglobin": 10.2,
            "cyp2d6": "PM",
            "cyp2c19": "IM",
            "medication_name": "Sertraline",
            "index_drug_dose": 50.0,
            "concomitant_drugs_count": 11,
            "polypharmacy_flag": 1,
            "prior_adr_history": 1,
            "cyp_inhibitors_flag": 1,
            "neurological_disease": 1,
            "hypertension": 1,
        },
        "healthy_adult": {
            "name": "Tom Lindqvist",
            "age": 27,
            "sex": "M",
            "ethnicity": "White",
            "height": 181.0,
            "weight": 76.0,
            "bmi": 23.2,
            "creatinine": 0.9,
            "egfr": 118.0,
            "ast_alt": 22.0,
            "bilirubin": 0.7,
            "albumin": 4.6,
            "cyp2c9": "Wild",
            "cyp2d6": "EM",
            "medication_name": "Ibuprofen",
            "index_drug_dose": 400.0,
            "concomitant_drugs_count": 0,
        },
    }

    if sample_type in samples:
        return jsonify(samples[sample_type]), 200

    return jsonify(
        {
            "status": "error",
            "message": f"Unknown sample profile '{sample_type}'.",
            "available": sorted(samples.keys()),
            "code": 404,
        }
    ), 404


@predict_bp.route("/get_drug_adrs", methods=["GET"])
def get_drug_adrs() -> Tuple[Response, int]:
    """Return known adverse drug reactions for medication query"""
    drug = request.args.get("drug", "Warfarin")
    adrs = ClinicalService.get_comprehensive_adr_list(drug)
    return jsonify({"drug": drug, "known_adrs": adrs}), 200
